* @

  ~@~ is a program that is used to execute a single command on a remote machine
  using [[https://en.wikipedia.org/wiki/Secure_Shell][ssh]].

  The command:

  #+BEGIN_EXAMPLE
  ssh HOST echo test
  #+END_EXAMPLE

  will produce exactly the same result as:

  #+BEGIN_EXAMPLE
  @ HOST echo test
  #+END_EXAMPLE

  The ~@~ program introduces the ~@~ /operator/. When a file is prefixed by the
  ~@~ operator, the file should be transferred to the remote location before
  the command is executed.

** Installation

   The program is depended on [[http://www.paramiko.org/][paramiko]], which can be installed with ~pip~
   using:

   #+BEGIN_EXAMPLE
   pip install paramiko
   #+END_EXAMPLE

   Then the program can be executed using:

   #+BEGIN_EXAMPLE
   python path/to/@.py
   #+END_EXAMPLE

   For simplicity I have the following alias in my =~/.bashrc=:

   #+BEGIN_EXAMPLE
   alias @='python /path/to/@.py'
   #+END_EXAMPLE

** Example

   Assume you have a file called ~hello~ containing ~hello world!~ in the
   current directory. If we run the command:

   #+BEGIN_EXAMPLE
   @ HOST cat @hello
   #+END_EXAMPLE

   the result will be:

   #+BEGIN_EXAMPLE
   hello world!
   #+END_EXAMPLE

** Notes

   ~@~ supports hosts specified in =~/.ssh/config=.

   If a command includes piping or redirections, these operators should be
   escaped:

   #+BEGIN_EXAMPLE
   @ HOST cat @hello \| rev
   #+END_EXAMPLE

   The result is:

   #+BEGIN_EXAMPLE
   !dlrow olleh
   #+END_EXAMPLE

* License

  The program is a generalization of [[https://github.com/peterbb/uio-print][uio-print]], from which a lot of source code
  has been borrowed.

  Copyright (c) 2016 Lars Tveito <larstvei@ifi.uio.no>

  Permission to use, copy, modify, and distribute this software for any
  purpose with or without fee is hereby granted.

  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
  ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
  OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
